require('angular');
require('./components/main.css');
require('./components/app');
require('./components/ftField/ftField');
require('./components/player/player');
require('./components/ball/ball');
require('./components/ftField/ftField.html');
require('./components/player/player.html');
require('./components/ball/ball.html');
